//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Appointment = new HashSet<Appointment>();
            this.UserAnimals = new HashSet<UserAnimals>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdGender { get; set; }
        public Nullable<int> IdTypeAni { get; set; }
        public Nullable<double> Weight_kg { get; set; }
        public Nullable<double> Height_cm { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual TypeAni TypeAni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAnimals> UserAnimals { get; set; }
    }
}
