//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnimals
    {
        public int ID { get; set; }
        public int IdUser { get; set; }
        public int IdAnimal { get; set; }
        public bool IsOwner { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Users Users { get; set; }
    }
}
